/*
 * EXTI.c
 *
 *  Created on: 14 ago. 2018
 *      Author: InDev
 */


#include "EXTI.h"

uint32_t printEXTI=0;
void EXTI_Line2(void)
{
	/*
	RCC_AHB1ENR->GPIOGEN=1;
	SYSCFG_EXTICR1->EXTI2=6; //PG2
	GPIOG_PUPDR->PUPDR2=1;
	GPIOG_MODER->MODER2=0;
	GPIOG_OSPEEDR->OSPEEDR2=3;
	GPIOG_OTYPER->OTYPER2=0;

	EXTI_IMR->IM2=1;
	EXTI_FTSR->TR2=1;

	NVIC_ISER0->NVIC_EXTI2=1;
	NVIC_IPR2->NVIC_EXTI2=15;




	RCC_AHB1ENR->GPIOGEN=1;
	SYSCFG_EXTICR1->EXTI3=6; //PG3
	GPIOG_PUPDR->PUPDR3=1;
	GPIOG_MODER->MODER3=0;
	GPIOG_OSPEEDR->OSPEEDR3=3;
	GPIOG_OTYPER->OTYPER3=0;

	RCC_AHB1ENR->GPIOBEN=1;
	GPIOB_PUPDR->PUPDR6=0;
	GPIOB_MODER->MODER6=1;
	GPIOB_OSPEEDR->OSPEEDR6=3;
	GPIOB_OTYPER->OTYPER6=0;
	GPIOB_ODR->ODR6=0;

	EXTI_IMR->IM3=1;
	EXTI_FTSR->TR3=1;

	NVIC_ISER0->NVIC_EXTI3=1;
	NVIC_IPR2->NVIC_EXTI3=15;


	RCC_AHB1ENR->GPIODEN=1;
	SYSCFG_EXTICR2->EXTI4=3; //PD4
	GPIOD_PUPDR->PUPDR4=1;
	GPIOD_MODER->MODER4=0;
	GPIOD_OSPEEDR->OSPEEDR4=3;
	GPIOD_OTYPER->OTYPER4=0;

	RCC_AHB1ENR->GPIOBEN=1;
	GPIOB_PUPDR->PUPDR7=0;
	GPIOB_MODER->MODER7=1;
	GPIOB_OSPEEDR->OSPEEDR7=3;
	GPIOB_OTYPER->OTYPER7=0;
	GPIOB_ODR->ODR7=0;

	EXTI_IMR->IM4=1;
	EXTI_FTSR->TR4=1;

	NVIC_ISER0->NVIC_EXTI4=1;
	NVIC_IPR2->NVIC_EXTI4=15;

	RCC_AHB1ENR->GPIODEN=1;
	SYSCFG_EXTICR2->EXTI5=3; //PD5
	GPIOD_PUPDR->PUPDR5=1;
	GPIOD_MODER->MODER5=0;
	GPIOD_OSPEEDR->OSPEEDR5=3;
	GPIOD_OTYPER->OTYPER5=0;



	EXTI_IMR->IM5=1;
	EXTI_FTSR->TR5=1;

	NVIC_ISER0->NVIC_EXTI9_5=1;
	NVIC_IPR5->NVIC_EXTI9_5=15;
*/

	RCC_AHB1ENR->GPIOHEN=1;
	GPIOH_PUPDR->PUPDR4=0;
	GPIOH_MODER->MODER4=1;
	GPIOH_OSPEEDR->OSPEEDR4=3;
	GPIOH_OTYPER->OTYPER4=0;
	GPIOH_ODR->ODR4=0;
	RCC_AHB1ENR->GPIOIEN=1;
	SYSCFG_EXTICR3->EXTI11=8; //PI11
	GPIOI_PUPDR->PUPDR11=1;
	GPIOI_MODER->MODER11=0;
	GPIOI_OSPEEDR->OSPEEDR11=3;
	GPIOI_OTYPER->OTYPER11=0;
/*
	RCC_AHB1ENR->GPIOIEN=1;
	GPIOI_PUPDR->PUPDR8=0;
	GPIOI_MODER->MODER8=1;
	GPIOI_OSPEEDR->OSPEEDR8=3;
	GPIOI_OTYPER->OTYPER8=0;
	GPIOI_ODR->ODR8=0;
*/
	EXTI_IMR->IM11=1;
	EXTI_FTSR->TR11=1;

	NVIC_ISER1->NVIC_EXTI15_10=1;
	NVIC_IPR10->NVIC_EXTI15_10=15;

}

__attribute__((section(".itcmram")))
void EXTI2_IRQHandler(void)
{
	static uint32_t aux=0;
	EXTI_PR->PR2=1;
	aux=EXTI_PR_R;
	printEXTI=1;
}


__attribute__((section(".itcmram")))
void EXTI3_IRQHandler(void)
{
	static uint32_t aux=0;
	EXTI_PR->PR3=1;
	aux=EXTI_PR_R;
	GPIOB_ODR->ODR6^=1;
}


__attribute__((section(".itcmram")))
void EXTI4_IRQHandler(void)
{
	static uint32_t aux=0;
	EXTI_PR->PR4=1;
	aux=EXTI_PR_R;
	GPIOB_ODR->ODR7^=1;
}



__attribute__((section(".itcmram")))
void EXTI9_5_IRQHandler(void)
{
	static uint32_t aux=0;
	if(EXTI_PR->PR5)
	{
		EXTI_PR->PR5=1;
		aux=EXTI_PR_R;
		//GPIOH_ODR->ODR4^=1;
	}

}


__attribute__((section(".itcmram")))
void EXTI15_10_IRQHandler(void)
{
	static uint32_t aux=0;
	if(EXTI_PR->PR11)
	{
		EXTI_PR->PR11=1;
		aux=EXTI_PR_R;
		printEXTI=1;
	}

}
