/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-08-01

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f746xx.h"
#include "CAMERA.h"
#include "USART.h"
#include "IMAGE_PROCESSING.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
uint32_t aux=1;
__attribute__((section(".data")))
uint8_t buffer4[60]=      "Programe Esta parte de codigo en SRAM1";
const uint8_t buffer3[60]="Programe Esta parte de codigo en FLASH";
__attribute__((section(".sram2")))
uint8_t buffer[100]=       "Programe Esta parte de codigo en SRAM2";
__attribute__((section(".dtcmram")))
uint8_t buffer1[100]=      "Programe Esta parte de codigo en DTCM";
__attribute__((section(".sdram")))
uint8_t buffer2[60]="Empty";
__attribute__((section(".data")))
uint8_t buffer5[60]={0xA,2,3,4,5,6,7,8,9,10,11,12,13,14,15};

int32_t frec=1000,frec1=0;

__attribute__((section(".sdram")))
char string4[10]={0,1,2};
uint32_t LTDC_layerBGBGX[2]={0};
uint32_t LTDC_layerBGBGY[2]={0};
uint32_t LTDC_layerBGX[2]={0};
uint32_t LTDC_layerBGY[2]={0};
LTDC_TFT_TypeDef* LTDC_layerBGSubLayer[40];
LTDC_TFT_TypeDef* LTDC_image3SubLayer[30];
LTDC_TFT_TypeDef* LTDC_image5SubLayer[30];


uint32_t lineBGX[2]={0};
uint32_t lineBGY[2]={0};
uint32_t radius[2]={0};
uint32_t triangleBGX[3]={10,90,180};
uint32_t triangleBGY[3]={20,100,20};


uint32_t lineHorizontalBGX2[2]={0};
uint32_t lineHorizontalBGY2[2]={0};


LTDC_DIMENSIONS_TypeDef dim;
LTDC_DIMENSIONS_TypeDef dim1;
LTDC_COORD_TypeDef coord;
LTDC_TFT_TypeDef image[40]={0};


LTDC_TFT_TypeDef layerBG={
	LTDC_Layer1, 			//Register
	0, 						//layerNum
	LTDC_Layer2_ADDRESS, 	//layerAddress
	0,

	0, //direccion de memoria inicial de la layer
	0, //direccion de memoria inicial de la layer
	0, //direccion de memoria inicial de la layer

	0xF800,					//layerAlphaConstant
	0x001F,					//layerAlphaConstant
	&font16x24,				//layerFont
	string4,

	1024,					//layerWidth
	600,					//layerHeight
	1024,					//layerWidthTotal
	600,					//layerHeightTotal

	2,
	0,
	(uint32_t*)LTDC_layerBGBGX,						//layerBGXi
	2,
	0,
	(uint32_t*)LTDC_layerBGBGY,						//layerBGYi
	2,
	0,
	(uint32_t*)LTDC_layerBGX,						//layerXi
	2,
	0,
	(uint32_t*)LTDC_layerBGY,						//layerYi
	0,						//SublayerCreated
	0,	//layerBG
	0,	//layerBG
	LAYER_TYPE_IMAGE_NOHEADER,
	0,
	0,
	LTDC_layerBGSubLayer,
	0,
	50,
	VARIABLETYPE_USHORT,
};
LTDC_TFT_TypeDef* layerBGP=&layerBG;
uint32_t counter=0,counter1=0;

const float32_t* a;

uint8_t* buff[4]={buffer,buffer1,(uint8_t*)buffer3,buffer4,};
uint8_t* buf;
uint32_t index1=0,i=0,j=0;
//a=sinTable_f32;
int main(void)
{

	//AREA_TypeDef* areas = (AREA_TypeDef*) (0xD0000000+0x7FF000);
	char* empresa="#InDeviceMex";
	char* creador="Eduardo Alvarez Lopez";
	char* aplicacion="Procesamiento Digital de Señales e Imagenes";
	char* Peripheral="Perifericos:";
	char* cpuFrec   ="CPU   : 200 MHz";
	char* sdramFrec ="SDRAM : 100 MHz";
	char* dcmi      ="DCMI and DMA2";
	char* ltdc      ="LTDC and DMA2D";
	char timestick[20];
	char timeCounter,counterClear;

	uint8_t kernel[25]={1,4,7,4,1,4,16,26,16,4,7,26,41,26,7,4,16,26,16,4,1,4,7,4,1};
	uint8_t kernel1[49]={0,0,1,2,1,0,0,
						 0,3,13,22,13,3,0,
						 1,13,59,97,59,13,1,
						 2,22,97,159,97,22,2,
						 1,13,59,97,59,13,1,
						 0,3,13,22,13,3,0,
						 0,0,1,2,1,0,0,
						};
	uint8_t kernel2[9]={1,2,1,2,4,2,1,2,1};


	char* Hardware="Hardware: waveshare ";
	char* Micro   ="STM32F743 ARM Cortex M7";
	char* camera  ="CAMARA: OV9655";
	char* tft     ="TFT   : 7\" 1024x600 ";

	float suma= {0.0};
	float histograma[256] = {0.0};
	AREA_TypeDef areas[100] = {0};
	__enable_irq();
	__NOP();
	//while(!SDRAM_Init());
	frec=RCC_GetHCLKFreq();
	frec=RCC_GetPCLK1Freq();
	frec=RCC_GetPCLK2Freq();
	frec=4450;
	SysTick_Initus(1000,1);
	DMA2D_Init();
	LTDC_Init();
	CAMERA_Init();

	Layer_AddSubLayer(LTDC_LayerBGP,layerBGP);
	Layer_Clear(LTDC_LayerBGP,COLOR_PURPLE);
	Layer_Clear(layerBGP,COLOR_PURPLE);



	image[2].layerTFT=layerBGP->layerTFT;
	image[2].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[2].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x80000;
	image[2].layerDataHue =(uint32_t)LTDC_LayerAux_ADDRESS+0x80000+0x80000;
	image[2].layerDataSaturation =(uint32_t)LTDC_LayerAux_ADDRESS+0x100000+0x80000;
	image[2].layerDataIntensity =(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x80000;
	image[2].layerXInit=0;
	image[2].layerYInit=0;
	image[2].layerBGXInit=13;
	image[2].layerBGYInit=13;
	image[2].layerWidth=240;
	image[2].layerHeight=320;
	image[2].layerWidthTotal=240;
	image[2].layerHeightTotal=320;
	image[2].variableType = VARIABLETYPE_USHORT;
	counter=Layer_AddSubLayer(layerBGP,&image[2]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);
/*
	image[19].layerTFT=layerBGP->layerTFT;
	image[19].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[19].layerDataAddress=(uint32_t)manos240x320;
	image[19].layerXInit=0;
	image[19].layerYInit=0;
	image[19].layerBGXInit=13;//image[19].layerBGXInit=1024-720-39;
	image[19].layerBGYInit=13;
	image[19].layerWidth=240;
	image[19].layerHeight=320;
	image[19].layerWidthTotal=240;
	image[19].layerHeightTotal=320;
	image[19].variableType = VARIABLETYPE_USHORT;
	counter=Layer_AddSubLayer(layerBGP,&image[19]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);
*/
	image[3].layerTFT=layerBGP->layerTFT;
	image[3].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[3].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x100000;
	image[3].layerXInit=0;
	image[3].layerYInit=0;
	image[3].layerBGXInit=1024-720-39;
	image[3].layerBGYInit=13;
	image[3].layerWidth=240;
	image[3].layerHeight=320;
	image[3].layerWidthTotal=240;
	image[3].layerHeightTotal=320;
	image[3].subLayersMaximum=20;
	image[3].subLayersCreated=0;
	image[3].variableType = VARIABLETYPE_USHORT;

	counter=Layer_AddSubLayer(layerBGP,&image[3]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);



	image[4].layerTFT=layerBGP->layerTFT;
	image[4].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[4].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x140000;
	image[4].layerXInit=0;
	image[4].layerYInit=0;
	image[4].layerBGXInit=1024-480-26;
	image[4].layerBGYInit=13;
	image[4].layerWidth=240;
	image[4].layerHeight=320;
	image[4].layerWidthTotal=240;
	image[4].layerHeightTotal=320;
	image[4].variableType = VARIABLETYPE_USHORT;
	counter=Layer_AddSubLayer(layerBGP,&image[4]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[5].layerTFT=layerBGP->layerTFT;
	image[5].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[5].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x180000;
	image[5].layerXInit=0;
	image[5].layerYInit=0;
	image[5].layerBGXInit=1024-240-13;
	image[5].layerBGYInit=13;
	image[5].layerWidth=240;
	image[5].layerHeight=320;
	image[5].layerWidthTotal=240;
	image[5].layerHeightTotal=320;
	image[5].variableType = VARIABLETYPE_USHORT;
	image[5].subLayers=LTDC_image5SubLayer;
	image[5].subLayersMaximum=20;
	image[5].subLayersCreated=0;
	counter=Layer_AddSubLayer(layerBGP,&image[5]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);







	image[6].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[6].layerFont=&font16x24;
	image[6].layerBGXInit=512-((11*16)/2);
	image[6].layerBGYInit=520;
	image[6].layerWidth=(12*16);
	image[6].layerHeight=25;
	image[6].layerString=empresa;
	image[6].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[6]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);



	image[25].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[25].layerFont=&font16x24;
	image[25].layerBGXInit=512-((25*16)/2);
	image[25].layerBGYInit=480;
	image[25].layerWidth=(25*16);
	image[25].layerHeight=25;
	image[25].layerString="DETECCION DE MANOS BASICO";
	image[25].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[25]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);


	image[7].layerTFT=layerBGP->layerTFT;
	image[7].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[7].layerFont=&font16x24;
	image[7].layerBGXInit=512-((21*16)/2);
	image[7].layerBGYInit=520+25;
	image[7].layerWidth=22*16;
	image[7].layerHeight=25;
	image[7].layerString=creador;
	image[7].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[7]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);


	image[8].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[8].layerFont=&font11x16;
	image[8].layerBGXInit=512-((43*11)/2);
	image[8].layerBGYInit=520+50;
	image[8].layerWidth=44*11;
	image[8].layerHeight=25;
	image[8].layerString=aplicacion;
	image[8].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[8]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);







	image[9].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[9].layerFont=&font11x16;
	image[9].layerBGXInit=10;
	image[9].layerBGYInit=500;
	image[9].layerWidth=13*11;
	image[9].layerHeight=17;
	image[9].layerString=Peripheral;
	image[9].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[9]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[10].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[10].layerFont=&font8x16;
	image[10].layerBGXInit=30;
	image[10].layerBGYInit=520;
	image[10].layerWidth=16*8;
	image[10].layerHeight=13;
	image[10].layerString=cpuFrec;
	image[10].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[10]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[11].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[11].layerFont=&font8x16;
	image[11].layerBGXInit=30;
	image[11].layerBGYInit=540;
	image[11].layerWidth=16*8;
	image[11].layerHeight=13;
	image[11].layerString=sdramFrec;
	image[11].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[11]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[12].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[12].layerFont=&font8x16_MS_Gothic;
	image[12].layerBGXInit=30;
	image[12].layerBGYInit=560;
	image[12].layerWidth=14*8;
	image[12].layerHeight=13;
	image[12].layerString=dcmi;
	image[12].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[12]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[13].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[13].layerFont=&font8x16_System;
	image[13].layerBGXInit=30;
	image[13].layerBGYInit=580;
	image[13].layerWidth=15*8;
	image[13].layerHeight=13;
	image[13].layerString=ltdc;
	image[13].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[13]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[14].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[14].layerFont=&font11x16;
	image[14].layerBGXInit=780;
	image[14].layerBGYInit=500;
	image[14].layerWidth=21*11;
	image[14].layerHeight=17;
	image[14].layerString=Hardware;
	image[14].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[14]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[15].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[15].layerFont=&font8x16;
	image[15].layerBGXInit=810;
	image[15].layerBGYInit=520;
	image[15].layerWidth=24*8;
	image[15].layerHeight=13;
	image[15].layerString=Micro;
	image[15].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[15]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[16].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[16].layerFont=&font8x16;
	image[16].layerBGXInit=810;
	image[16].layerBGYInit=540;
	image[16].layerWidth=15*8;
	image[16].layerHeight=13;
	image[16].layerString=camera;
	image[16].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[16]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[17].layerType=LAYER_TYPE_STRING_SIMPLE;
	image[17].layerFont=&font8x16;
	image[17].layerBGXInit=810;
	image[17].layerBGYInit=560;
	image[17].layerWidth=25*8;
	image[17].layerHeight=13;
	image[17].layerString=tft;
	image[17].layerColorFont=COLOR_YELLOW;
	counter=Layer_AddSubLayer(layerBGP,&image[17]);
	timeCounter=counter;
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);


	image[17].layerFont=&font11x16;
	image[17].layerWidth=240;
	image[17].layerHeight=60;
	image[17].layerBGYInit=360;

	image[17].layerBGXInit=(266/2)-((17*11)/2);
	image[17].layerString="[Imagen Rotacion]";
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[17].layerBGXInit=253+(266/2)-((18*11)/2);
	image[17].layerString="[  Local Binary  \n\r  Patterns Uniform]";
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[17].layerBGXInit=253+253+(266/2)-((19*11)/2);
	image[17].layerString="[Gauss Filter 3x3\n\r      LBPU     ]";
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[17].layerBGXInit=253+253+253+(266/2)-((20*11)/2);
	image[17].layerString="[Gauss Filter 5x5\n\r      LBPU     ]";
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[18].layerTFT=layerBGP->layerTFT;
	image[18].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[18].layerBGXInit=512-((43*11)/2)-10;
	image[18].layerBGYInit=520-10;
	image[18].layerWidth=(43*11)+20;
	image[18].layerHeight=90;
	image[18].layerRadiusInit=10;
	image[18].layerColorBG=COLOR_ORANGE;
	counter=Layer_AddSubLayer(layerBGP,&image[18]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);





	image[20].layerTFT=layerBGP->layerTFT;
	image[20].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[20].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x1C0000;
	image[20].layerXInit=0;
	image[20].layerYInit=0;
	image[20].layerBGXInit=0;
	image[20].layerBGYInit=0;
	image[20].layerWidth=240;
	image[20].layerHeight=320;
	image[20].layerWidthTotal=240;
	image[20].layerHeightTotal=320;
	image[20].variableType = VARIABLETYPE_UCHAR;


	image[21].layerTFT=layerBGP->layerTFT;
	image[21].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[21].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x200000;
	image[21].layerXInit=0;
	image[21].layerYInit=0;
	image[21].layerBGXInit=0;
	image[21].layerBGYInit=0;
	image[21].layerWidth=240;
	image[21].layerHeight=320;
	image[21].layerWidthTotal=240;
	image[21].layerHeightTotal=320;
	image[21].variableType = VARIABLETYPE_UCHAR;


	image[22].layerTFT=layerBGP->layerTFT;
	image[22].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[22].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x180000+0x240000;
	image[22].layerXInit=0;
	image[22].layerYInit=0;
	image[22].layerBGXInit=0;
	image[22].layerBGYInit=0;
	image[22].layerWidth=240;
	image[22].layerHeight=320;
	image[22].layerWidthTotal=240;
	image[22].layerHeightTotal=320;
	image[22].variableType = VARIABLETYPE_UCHAR;


	image[32].layerTFT=layerBGP->layerTFT;
	image[32].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[32].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x80000+0x80000;
	image[32].layerXInit=0;
	image[32].layerYInit=0;
	image[32].layerBGXInit=0;
	image[32].layerBGYInit=0;
	image[32].layerWidth=240;
	image[32].layerHeight=320;
	image[32].layerWidthTotal=240;
	image[32].layerHeightTotal=320;
	image[32].variableType = VARIABLETYPE_UCHAR;


	image[33].layerTFT=layerBGP->layerTFT;
	image[33].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[33].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x80000+0xC0000;
	image[33].layerXInit=0;
	image[33].layerYInit=0;
	image[33].layerBGXInit=0;
	image[33].layerBGYInit=0;
	image[33].layerWidth=240;
	image[33].layerHeight=320;
	image[33].layerWidthTotal=240;
	image[33].layerHeightTotal=320;
	image[33].variableType = VARIABLETYPE_UCHAR;



	image[34].layerTFT=layerBGP->layerTFT;
	image[34].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[34].layerDataAddress=(uint32_t)LTDC_LayerAux_ADDRESS+0x80000+0x100000;
	image[34].layerXInit=0;
	image[34].layerYInit=0;
	image[34].layerBGXInit=0;
	image[34].layerBGYInit=0;
	image[34].layerWidth=240;
	image[34].layerHeight=320;
	image[34].layerWidthTotal=240;
	image[34].layerHeightTotal=320;
	image[34].variableType = VARIABLETYPE_UCHAR;

	image[23].layerTFT=layerBGP->layerTFT;
	image[23].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[23].layerBGXInit=0;
	image[23].layerBGYInit=0;
	image[23].layerWidth=240+13+13;
	image[23].layerHeight=320+13+13;
	image[23].layerRadiusInit=13;
	image[23].layerColorBG=COLOR_ORANGE;
	counter=Layer_AddSubLayer(layerBGP,&image[23]);
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[23].layerTFT=layerBGP->layerTFT;
	image[23].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[23].layerBGXInit=240+13;
	image[23].layerBGYInit=0;
	image[23].layerWidth=240+13+13;
	image[23].layerHeight=320+13+13;
	image[23].layerRadiusInit=10;
	image[23].layerColorBG=COLOR_ORANGE;
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[23].layerTFT=layerBGP->layerTFT;
	image[23].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[23].layerBGXInit=480+26;
	image[23].layerBGYInit=0;
	image[23].layerWidth=240+13+13;
	image[23].layerHeight=320+13+13;
	image[23].layerRadiusInit=13;
	image[23].layerColorBG=COLOR_ORANGE;
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[23].layerTFT=layerBGP->layerTFT;
	image[23].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[23].layerBGXInit=1024-240-13-13;
	image[23].layerBGYInit=0;
	image[23].layerWidth=240+13+13;
	image[23].layerHeight=320+13+13;
	image[23].layerRadiusInit=13;
	image[23].layerColorBG=COLOR_ORANGE;
	Layer_RefreshSubLayer(layerBGP,counter);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);


	image[24].layerTFT=layerBGP->layerTFT;
	image[24].layerType=LAYER_TYPE_RECTANGLE_SEMI;
	image[24].layerBGXInit=0;
	image[24].layerBGYInit=0;
	image[24].layerWidth=100;
	image[24].layerHeight=100;
	image[24].layerRadiusInit=10;
	image[24].layerColorBG=COLOR_WHITE;
	Layer_AddSubLayer(&image[5],&image[24]);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);

	image[28].layerTFT=layerBGP->layerTFT;
	image[28].layerType=LAYER_TYPE_RECTANGLE_FILL;
	image[28].layerBGXInit=0;
	image[28].layerBGYInit=450;
	image[28].layerWidth=1023;
	image[28].layerHeight=20;
	image[28].layerColorBG=COLOR_PURPLE;
	counterClear=Layer_AddSubLayer(layerBGP,&image[28]);
	Layer_RefreshSubLayer(layerBGP,counterClear);
	Layer_RefreshSubLayer(LTDC_LayerBGP,1);



	image[29].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[29].layerDataAddress=(uint32_t)kernel2;
	image[29].layerXInit=0;
	image[29].layerYInit=0;
	image[29].layerBGXInit=0;
	image[29].layerBGYInit=0;
	image[29].layerWidth=3;
	image[29].layerHeight=3;
	image[29].layerWidthTotal=3;
	image[29].layerHeightTotal=3;
	image[29].variableType = VARIABLETYPE_UCHAR;

	image[30].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[30].layerDataAddress=(uint32_t)kernel;
	image[30].layerXInit=0;
	image[30].layerYInit=0;
	image[30].layerBGXInit=0;
	image[30].layerBGYInit=0;
	image[30].layerWidth=5;
	image[30].layerHeight=5;
	image[30].layerWidthTotal=5;
	image[30].layerHeightTotal=5;
	image[30].variableType = VARIABLETYPE_UCHAR;

	image[31].layerType=LAYER_TYPE_IMAGE_NOHEADER;
	image[31].layerDataAddress=(uint32_t)kernel2;
	image[31].layerXInit=0;
	image[31].layerYInit=0;
	image[31].layerBGXInit=0;
	image[31].layerBGYInit=0;
	image[31].layerWidth=5;
	image[31].layerHeight=5;
	image[31].layerWidthTotal=5;
	image[31].layerHeightTotal=5;
	image[31].variableType = VARIABLETYPE_UCHAR;


	EXTI_Line2();
	USART_Init();


	image[17].layerWidth=16*4;
	image[17].layerHeight=13;
	image[17].layerFont=&font8x16_MS_Gothic;
	image[17].layerBGYInit=450;

	dim.X[0]=0;
	dim.X[1]=0;
	dim.Y[0]=0;
	dim.Y[1]=0;
	dim.width=320;
	dim.height=240;

	dim1.X[0]=0;
	dim1.X[1]=0;
	dim1.X[2]=0;
	dim1.X[3]=0;
	dim1.Y[0]=0;
	dim1.Y[1]=0;
	dim1.Y[2]=0;
	dim1.Y[3]=0;
	dim1.width=240;
	dim1.height=320;
	while (1)
	{




/*
		Layer_RefreshSubLayer(layerBGP,counterClear);

		frec=SysTick_Count();
		dim1.X[0]=0;
		dim1.X[1]=0;
		dim1.Y[0]=0;
		dim1.Y[1]=0;
		dim1.width=240;
		dim1.height=80;
		IMAGEPROC_16bGrayWorld(&image[19],&image[3],dim1);

		frec1=SysTick_Count();
		frec=(frec1-frec)*4;
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=256+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=256+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);


		frec=SysTick_Count();
		IMAGEPROC_16bUmbral(&image[3],&image[4],dim1,0x7204,0xE,0x13,0xa);

		frec1=SysTick_Count();
		frec=(frec1-frec)*4;
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=(256*2)+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=(256*2)+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);



		frec=SysTick_Count();
		int cantidad= IMAGEPROC_16bConectivity8(&image[4],&image[5],dim1,areas);


		for(int h=0; h<cantidad; h++)
		{
			if(areas[h].area>100)
			{
				image[24].layerBGXInit=areas[h].Xmin;
				image[24].layerBGYInit=areas[h].Ymin;
				image[24].layerWidth=areas[h].Xmax-areas[h].Xmin;
				image[24].layerHeight=areas[h].Ymax-areas[h].Ymin;
				Layer_RefreshSubLayer(&image[5],1);
			}
		}

		frec1=SysTick_Count();
		frec=(frec1-frec)*4;
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=(256*3)+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=(256*3)+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		dim1.X[0]=0;
		dim1.X[1]=0;
		dim1.Y[0]=80;
		dim1.Y[1]=80;
		dim1.width=240;
		dim1.height=80;
		IMAGEPROC_16bGrayWorld(&image[19],&image[3],dim1);
		IMAGEPROC_16bUmbral(&image[3],&image[4],dim1,0x7204,0xc,0x13,0xa);
		cantidad= IMAGEPROC_16bConectivity8(&image[4],&image[5],dim1,areas);

		for(int h=0; h<cantidad; h++)
		{
			if(areas[h].area>100)
			{
				image[24].layerBGXInit=areas[h].Xmin;
				image[24].layerBGYInit=areas[h].Ymin;
				image[24].layerWidth=areas[h].Xmax-areas[h].Xmin;
				image[24].layerHeight=areas[h].Ymax-areas[h].Ymin;
				Layer_RefreshSubLayer(&image[5],1);
			}
		}

		dim1.X[0]=0;
		dim1.X[1]=0;
		dim1.Y[0]=160;
		dim1.Y[1]=160;
		dim1.width=240;
		dim1.height=80;
		IMAGEPROC_16bGrayWorld(&image[19],&image[3],dim1);
		IMAGEPROC_16bUmbral(&image[3],&image[4],dim1,0x7204,0xE,0x13,0xa);
		cantidad= IMAGEPROC_16bConectivity8(&image[4],&image[5],dim1,areas);

		for(int h=0; h<cantidad; h++)
		{
			if(areas[h].area>100)
			{
				image[24].layerBGXInit=areas[h].Xmin;
				image[24].layerBGYInit=areas[h].Ymin;
				image[24].layerWidth=areas[h].Xmax-areas[h].Xmin;
				image[24].layerHeight=areas[h].Ymax-areas[h].Ymin;
				Layer_RefreshSubLayer(&image[5],1);
			}
		}

		dim1.X[0]=0;
		dim1.X[1]=0;
		dim1.Y[0]=240;
		dim1.Y[1]=240;
		dim1.width=240;
		dim1.height=80;
		IMAGEPROC_16bGrayWorld(&image[19],&image[3],dim1);
		IMAGEPROC_16bUmbral(&image[3],&image[4],dim1,0x7204,0xE,0x13,0xa);
		cantidad= IMAGEPROC_16bConectivity8(&image[4],&image[5],dim1,areas);

		for(int h=0; h<cantidad; h++)
		{
			if(areas[h].area>100)
			{
				image[24].layerBGXInit=areas[h].Xmin;
				image[24].layerBGYInit=areas[h].Ymin;
				image[24].layerWidth=areas[h].Xmax-areas[h].Xmin;
				image[24].layerHeight=areas[h].Ymax-areas[h].Ymin;
				Layer_RefreshSubLayer(&image[5],1);
			}
		}

		Layer_RefreshSubLayer(layerBGP,1);
		Layer_RefreshSubLayer(layerBGP,2);
		Layer_RefreshSubLayer(layerBGP,3);
		Layer_RefreshSubLayer(layerBGP,4);
		Layer_RefreshSubLayer(layerBGP,5);
		Layer_RefreshSubLayer(LTDC_LayerBGP,1);

*/



















		Layer_RefreshSubLayer(layerBGP,counterClear);

		frec=SysTick_Count();
		//Layer_Clear(layerBGP,COLOR_BLACK);
		IMAGEPROC_Rotation90Degree(DCMIProcess,&image[2],dim);
		IMAGEPROC_16bRGBScale28bGrayScale(&image[2],&image[20],dim1);

		frec1=SysTick_Count();
		frec=(frec1-frec);
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);
		GPIOH_ODR_R&=~ GPIOH_ODR_R_ODR4_HIGH;




		frec=SysTick_Count();

		IMAGEPROC_Convolucion(&image[20],&image[22],&image[29],dim1);
		IMAGEPROC_Convolucion(&image[22],&image[21],&image[30],dim1);
		IMAGEPROC_LBPU(&image[21],&image[32],dim1);
		IMAGEPROC_8bGrayScale216bGrayScale(&image[32],&image[3],dim1);
		frec1=SysTick_Count();
		frec=(frec1-frec);
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=(256*1)+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=(256*1)+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);


/*
		frec=SysTick_Count();


		//IMAGEPROC_Get16bRGBScaleHSI(&image[2],&image[2],dim1);
		IMAGEPROC_Convolucion(&image[20],&image[21],&image[29],dim1);
		IMAGEPROC_LBPU(&image[21],&image[22],dim1);
		IMAGEPROC_8bGrayScale216bGrayScale(&image[22],&image[4],dim1);

		frec1=SysTick_Count();
		frec=(frec1-frec);
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=(256*2)+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=(256*2)+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);


		frec=SysTick_Count();

		IMAGEPROC_Convolucion(&image[20],&image[33],&image[30],dim1);
		IMAGEPROC_LBPU(&image[33],&image[34],dim1);

		IMAGEPROC_8bGrayScale216bGrayScale(&image[34],&image[5],dim1);

		frec1=SysTick_Count();
		frec=(frec1-frec);
		CONV_u8UIntToString(frec,(int8_t*)timestick);
		image[17].layerBGXInit=(256*3)+100;
		image[17].layerString=timestick;
		Layer_RefreshSubLayer(layerBGP,timeCounter);

		image[17].layerBGXInit=(256*3)+140;
		image[17].layerString=" ms";
		Layer_RefreshSubLayer(layerBGP,timeCounter);


		Layer_RefreshSubLayer(layerBGP,3);
		Layer_RefreshSubLayer(layerBGP,4);


		GPIOH_ODR_R&=~ GPIOH_ODR_R_ODR4_HIGH;
*/
		//IMAGEPROC_GetHSI16bRGBScale(&image[2],&image[4],dim1);
		//IMAGEPROC_Flip(&image[2],&image[3],dim1);

		//GPIOH_ODR->ODR4^=1;
		//IMAGEPROC_16bRGBScaleSplitFullRed(&image[2],&image[20],&dim1);
		//IMAGEPROC_16bRGBScaleSplitFullGreen(&image[2],&image[21],&dim1);
		//IMAGEPROC_16bRGBScaleSplitFullBlue(&image[2],&image[22],&dim1);
		//IMAGEPROC_8bRedFullto16bRGBScale(&image[20],&image[3],&dim1);
		//IMAGEPROC_8bGreenFullto16bRGBScale(&image[21],&image[3],&dim1);
		//IMAGEPROC_8bBlueFullto16bRGBScale(&image[22],&image[3],&dim1);

		//IMAGEPROC_8bRGBFullto16bRGBScale(&image[20],&image[21],&image[22],&image[3],&dim1);
		//IMAGEPROC_16bRGBScale28bGrayScale(&image[19],&image[21],&dim1);
		//IMAGEPROC_8bAdd(&image[20],&image[21],&image[20],&dim1,0xFF);
		//IMAGEPROC_16bRGBScale216bGrayScale(&image[2],&image[5],dim1);
		//IMAGEPROC_16bGrayWorld(&image[2],&image[5],dim1);
		//IMAGEPROC_8bGrayScale216bGrayScale(&image[20],&image[4],&dim1);
		//IMAGEPROC_16bRGBScale216bGrayScaleBlue(&image[2],&image[4],&dim1);
		//IMAGEPROC_16bRGBScale216bGrayScaleGreen(&image[2],&image[5],&dim1);
		//IMAGEPROC_16bAddMeanBlend(&image[2],&image[19],&image[4],&dim1,0.9);
		//IMAGEPROC_16bAdd(&image[2],&image[19],&image[4],dim1);


		//IMAGEPROC_16bGrayWorld(&image[2],&image[5],dim1);
		//IMAGEPROC_16bUmbral(&image[5],&image[5],dim1,0x7204,0xE,0x13,0xA);
		//IMAGEPROC_16bUmbral(&image[4],&image[4],dim1,0x7204,0xE,0x13,0xA);

		//IMAGEPROC_16bAddMean(&image[2],&image[19],&image[5],&dim1);
		//IMAGEPROC_Get16bRGBScaleHSI(&image[2],&image[2],&dim1);
		//IMAGEPROC_16bRGBScale216bGrayScaleRed(&image[2],&image[3],&dim1);
		//IMAGEPROC_GetHSI16bRGBScale(&image[2],&image[4],&dim1);
		//IMAGEPROC_16bRGBScale216bGrayScaleGreen(&image[2],&image[4],&dim1);
		//IMAGEPROC_16bRGBScale216bGrayScaleBlue(&image[2],&image[5],&dim1);
		//counter=Random16();
		//Layer_RefreshSubLayer(layerBGP,3);
		//Layer_RefreshSubLayer(layerBGP,4);
		//LTDC_Refresh();
		Layer_RefreshSubLayer(layerBGP,1);
		Layer_RefreshSubLayer(layerBGP,2);
		Layer_RefreshSubLayer(LTDC_LayerBGP,1);


	}
}





